version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run tests
          command: jest