version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    machine:
      enabled: true
    working_directory: ~/happy_quotes
    environment: $HEROKU_APP_NAME
    steps:
      - checkout
      - run:
          name: Setup Heroku
          command: bash .circleci/setup-heroku.sh
      - run:
          name: Push to Heroku
          command: |
            git push heroku $HEROKU_APP_NAME:main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build