version: 2.0
jobs:
  build:
    docker:
      - image: cimg/node:16.0.0
    steps:
      - checkout
      - run: node --version
      - run:
          name: install packages
          command: npm install
      - run:
          name: Run tests
          command: npm test
  deploy:
    steps:
      - checkout
      - run:
          command: |
            git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git main

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build